project:
  type: website
  output-dir: docs
  
website:
  title: "Anna Weissman"
  navbar:
    left:
      - href: index.html
        text: About
      - href: cv.html
        text: CV
      - href: research.html
        text: Research
      - href: teaching.html
        text: Teaching
      - href: data.html
        text: Data
      
format:
  html:
    css: styles.css
    theme: cosmo
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">


editor: visual

