project:
  type: website
  output-dir: docs
  
website:
  title: "Anna Weissman"
  favicon: images/aw-favicon.svg
  navbar:
    left:
      - href: index.html
        text: About
      - href: cv.html
        text: CV
      - href: research.html
        text: Research
      - href: teaching.html
        text: Teaching
      - href: data.html
        text: Data
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

