---
title: "Research"
format:
  html:
    css: styles.css
---

### [Peer-Reviewed Articles]{.underline}

\normalsize Descriptive Representation in an Era of Polarization <span class="citation-text">(2025). Anna Weissman. *The Journal of Politics*</span>
<details>

<summary>[Abstract]{style="font-size:0.8em"} <a href="papers/Weissman_JOP_2025.pdf" target="_blank" title="Download PDF" style="margin-left:8px;"> <i class="fa-solid fa-file-pdf"></i> </a> <a href="https://www.journals.uchicago.edu/doi/10.1086/732961" target="_blank" title="Publisher page" style="margin-left:8px;"> <i class="fa-solid fa-link"></i> </a></summary>

Studies of descriptive representation find that voters more positively evaluate representatives who share their ascriptive characteristics. I argue that this pattern can be upended when voters develop more positive affect towards outgroups. In the United States, Democrats have increasingly expressed more positive views towards marginalized groups, while Republicans' attitudes about these groups have not shifted. Under such conditions, my argument predicts that the effect of representatives' race and gender on constituent evaluations should vary more by constituents' partisanship than by their own ascriptive characteristics. Applying a difference-in-differences design to 2008-2020 CCES data, I find that Democrats of all backgrounds now approve more highly of Congressmembers from historically marginalized groups, whereas Republicans' approval is unrelated to Member identity. Democrats also give women and minority representatives leeway to diverge ideologically. These findings demonstrate that polarizing attitudes about race and gender can disrupt classic patterns in how constituents evaluate representatives.

</details>

\normalsize As Racial Attitudes Go, So Goes Approval: Why White Democrats Favor Representatives of Color <span class="citation-text">(2025). Anna Weissman and Anna Mikkelborg. *Political Behavior*.</span>
<details>

<summary>[Abstract]{style="font-size:0.8em"} <a href="papers/Weissman&Mikkelborg_Behavior_2025.pdf" target="_blank" title="Download PDF" style="margin-left:8px;"> <i class="fa-solid fa-file-pdf"></i> </a> <a href="https://doi.org/10.1007/s11109-025-10098-4" target="_blank" title="Publisher page" style="margin-left:8px;"> <i class="fa-solid fa-link"></i> </a></summary>

Recent research shows that white Democrats have become more approving of politicians of color compared to white politicians in the last decade, in contrast with past research indicating that white voters typically prefer white representatives. White voters’ support for politicians of color has long been linked to their racial attitudes, implying that this change could be a result of white Democrats’ increasing racial liberalism. This mechanism deserves more than speculation, since understanding the cause of this shift influences expectations about its likely durability and broader implications for racial politics. This paper provides evidence of the persistence of this shift and evaluates the most plausible potential mechanisms behind it. We find that racial attitudes are strongly associated with white Democrats’ greater approval of representatives of color at the individual level and over time, while there is little evidence that either ideological stereotyping or differences in legislator quality are responsible. These results provide evidence that white Democrats' increasing racial liberalism influences consequential political opinions like support for representatives of color.

</details>

\normalsize When Do Local Interest Groups Participate in the Housing Entitlement Process? <span class="citation-text">(2024). Michael Hankinson, Asya Magazinnik and Anna Weissman. *Journal of Political Institutions and Political Economy*. </span>
<details>

<summary>[Abstract]{style="font-size:0.8em"} <a href="papers/Hankinson-Magazinnik-Weissman_JPIPE_2024.pdf" target="_blank" title="Download PDF" style="margin-left:8px;"> <i class="fa-solid fa-file-pdf"></i> </a> <a href="http://dx.doi.org/10.1561/113.00000093" target="_blank" title="Publisher page" style="margin-left:8px;"> <i class="fa-solid fa-link"></i> </a></summary>

Local governments control a hidden flow of economic goods that never appear on city budgets. Through the housing entitlement process, city officials may condition approval on the benefits developers provide to organized interests. But the politics and policies created by this discretionary review have yet to be studied through the lens of interest group mobilization. We bridge this gap with an analysis of the behavior of construction unions in the housing entitlement process. Using data from 164 U.S. cities, we find that construction union representatives are more likely to attend public meetings to advocate for favorable labor agreements when the expected profitability of new housing developments is high — and thus, when there are more particularistic benefits on the table. While interest group competition within local participatory institutions may signal a robust, pluralist democracy, it also risks driving up housing costs, to the detriment of both organized and unorganized residents.

</details>

### [Working Papers & Works in Progress]{.underline}

Local Roots in Local Politics
<details>

```{=html}
<!----
<summary><strong>[Abstract]{style="font-size:0.8em"}</strong> <a href="https://www.dropbox.com/scl/fi/l8ejn2t02y6jpzqvdw923/Weissman_Roots_LatestDraft.pdf?rlkey=qmij2kdhb4sa5eqf3f1a45acl&st=vw2xomcs&dl=0 "
       target="_blank" rel="noopener noreferrer"
       title="Latest draft" style="margin-left:8px;"> <i class="fa-brands fa-dropbox"></i> </a></summary>
--->
```

```{=html}
<!---
<summary><strong>[Abstract]{style="font-size:0.8em"}</strong> <a href="papers/Weissman_Roots_LatestDraft.pdf" target="_blank" title="Download PDF" style="margin-left:8px;"> <i class="fa-solid fa-file-pdf"></i> </a></summary>
--->
```

<summary>[Abstract]{style="font-size:0.8em"}</summary>

Local decision-making is enormously consequential. Yet who runs for and wins local office remains understudied. Given local officials’ place-based responsibilities, I argue that local roots operate as a de facto requirement for candidacy. Using novel datasets of municipal campaign statements, linked voter file and candidate records, and original nationwide surveys of elected officials and constituents, I show that local roots overwhelmingly shape who runs for office, how candidates present themselves to voters, and who ultimately governs, with roots predicting candidacy and officeholding more strongly than race, gender, or age. But while voters of all backgrounds appear to prefer long-term residents in office, the descriptive overrepresentation of deeply rooted constituents may also translate into substantive underrepresentation for newcomers. I trace such consequences in the area of land use. These findings suggest that research on local politics should contend with the theoretical and substantive implications of this powerful bias towards longtime residents.

</details>

When Partisanship Matters in Local Politics
<details>

<summary>[Abstract]{style="font-size:0.8em"}</summary>

Recent scholarship challenges the traditional view that partisanship has little influence on local governance, showing that officials' party affiliation affects municipal decision-making. However, the explanations for why partisanship matters often assume conditions present only in certain types of municipalities. I argue that partisanship matters most in large cities, where the scope of governance creates the context for partisan division, while smaller municipalities focus on managerial concerns with limited partisan conflict. Using an original survey of 1,280 elected officials, paired with local council meeting transcripts and a novel dataset of candidate statements, I find that partisan divides emerge primarily in larger cities on nationally salient issues, whereas smaller municipalities show little evidence of partisan policymaking. These findings bridge perspectives from early work and recent scholarship by demonstrating that partisan influence in local governance is context-dependent. This research refines our understanding of when and why national political dynamics impact local democracy.

</details>

Place-Based Connection and the Politics of Housing
<details>

<summary>[Abstract]{style="font-size:0.8em"}</summary>

Opposition to housing development has long been explained by material self-interest and exclusionary attitudes, but scholars have recently proposed alternatives, such as aesthetic preferences. This paper offers an additional explanation for preservationist attitudes: place-based connection. Material, psychological, and social connections to place can produce an aversion to change that limits growth. Using an original survey of more than 1,000 registered voters across small-town and suburban municipalities with opportunities for growth, I generate six indices of place-based connection that are not strongly associated with one another nor with characteristics such as race, gender, or party. I find that distinct dimensions of place-based connection explain different preservationist attitudes: psychological attachment is the strongest and most consistent predictor, while long-term residency and growing up in a place matter most in growing communities where newcomers are salient. The paper develops a framework for understanding how place-based connection contributes to the politics of growth.

</details>

New in Town? An Experiment on Local Legislators’ Responsiveness to Newcomers and Locals (with Gustavo Novoa)

How Local Officials (Mis)perceive the Politics and Economics of Growth (with David Broockman and Christopher Elmendorf)

Book Project: How Place Conditions Local Politics: Understanding Local Power and Decision-Making Beyond Party Lines
